-- ============================================================
-- LEDGER PLACEHOLDER — NO STATEMENTS, BY DESIGN
-- ============================================================
-- Version : 20260814165457
-- Name    : center_headcount
--
-- This migration WAS applied to production. Its SQL was never committed
-- under this version number, so the Supabase CLI reported it as
-- "Remote migration versions not found in local migrations directory"
-- and the Supabase Preview check failed on every commit to main.
--
-- This file closes that gap HONESTLY: it records that the version exists
-- and says where its DDL actually lives. It deliberately contains no
-- executable statements, because inventing SQL to match a schema nobody
-- captured would be worse than the gap — a rebuild would then differ from
-- production silently instead of loudly.
--
-- ⚠️ THE MIGRATIONS DIRECTORY IS NOT A REBUILD SOURCE. It has not been one
-- since before the ledger started (see supabase/migrations/README.md).
-- To reproduce this database, restore a backup; do not replay this folder.
--
-- Where the DDL actually lives:
--   * 20260816032623_center_headcount_admin.sql
--   * 20260816032659_center_headcount_admin_fix_attendance_join.sql
--   * staff_injury_and_headcount.sql
--
-- (Found by searching the folder for this migration's name. The file
--  above carries the statements; it is simply committed under a
--  different name than the version the database recorded.)
--
-- ============================================================
